version: '2.1'
services:
  
  wso2_container:
   image: wso2/wso2am:latest
   container_name: wso2
   ports:
     - "9443:9443"
     - "8243:8243"
     - "8280:8280"
     - "5005:5005"
 
   environment:
     - USER=root
   networks:
       site2_mynet:
         ipv4_address: 172.28.5.32    
   volumes:
     - wso2_data2:/home/wso2carbon/wso2am-4.0.0/repository/deployment/server/
     - wso2_conf2:/home/wso2carbon/wso2am-4.0.0/repository/conf/
     - ./config/log4j2.properties:/home/wso2carbon/wso2am-4.0.0/repository/conf/log4j2.properties
     - ./config/deployment.toml:/home/wso2carbon/wso2am-4.0.0/repository/conf/deployment.toml
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      site2_mynet:
         ipv4_address: 172.28.5.30

networks:
  site2_mynet:
    external: true
volumes:
  wso2_data2:
  wso2_conf2:
